export const usersToCreate = ['Nikunj', 'Digambar', 'Aarya', 'Prathamesh', 'Adarsh'];

export const threadSummaries = {
  'Frontend': 'Focuses on React+Vite setup, state management, component library integration, and UI design for the dashboard.',
  'Backend': 'Focuses on the Node.js API, database schema, transaction management, query optimization, and authentication strategy.',
  'Infrastructure': 'Handles AWS cloud deployment, ECS Fargate configuration, CI/CD with GitHub Actions, and system monitoring.',
  'Integrations': 'Dedicated to third-party integrations like payment gateways (Stripe) and compliance document signing (DocuSign/HelloSign).',
  'Testing': 'Dedicated to QA cycles, Cypress end-to-end testing, security vulnerability scanning, and load testing.'
};

export const stage1_ideation = [
  { thread: 'Main', user: 'Nikunj', text: 'Hey team, let\'s kick off the BuildBoard project today. The goal is to build a B2B SaaS platform for construction companies to manage projects, subcontractors, bids, and compliance documents.' },
  { thread: 'Main', user: 'Digambar', text: 'Exciting. What\'s the core flow for a subcontractor?' },
  { thread: 'Main', user: 'Nikunj', text: 'Subcontractors will log in, view available projects, submit financial bids, and upload their compliance/insurance documents for approval.' },
  { thread: 'Main', user: 'Prathamesh', text: 'For the compliance documents, do we require third-party verification?' },
  { thread: 'Main', user: 'Nikunj', text: 'Yes, but that\'s a tricky area.' },
  { thread: 'Main', user: 'Aarya', text: 'If we use a third-party API for all compliance checks, we need to think about GDPR carefully. If we send PII outward without proper consent mechanisms, it could become a compliance nightmare.' },
  { thread: 'Main', user: 'Prathamesh', text: 'Good point. We might want to keep the primary document storage on our end and only send hashed data or specific public metadata for verification?' },
  { thread: 'Main', user: 'Nikunj', text: 'Exactly. Let\'s keep storage local to our S3 buckets. Meanwhile, we need to decide on our database architecture.' },
  { thread: 'Main', user: 'Adarsh', text: 'Are we leaning towards a microservices approach to let bids scale independently?' },
  { thread: 'Main', user: 'Nikunj', text: 'A monolith might be better for v1 speed, but let\'s debate the DB first.' },
  { thread: 'Main', user: 'Digambar', text: 'What about MongoDB? It is great for the flexibility we might need if compliance documents have completely unpredictable metadata formats.' },
  { thread: 'Main', user: 'Nikunj', text: 'Given we need complex relational queries across projects, subcontractors, and bids with strict consistency, I think Postgres is the right call here.' },
  { thread: 'Main', user: 'Digambar', text: 'What about the document flexibility we were just talking about for compliance files?' },
  { thread: 'Main', user: 'Nikunj', text: 'We can use JSONB columns in Postgres for that — we get both relational integrity and document flexibility.', isDecision: true },
  { thread: 'Main', user: 'Prathamesh', text: 'Agreed, and it makes our automated backup strategy dramatically simpler too.' },
  { thread: 'Main', user: 'Aarya', text: 'I\'ll handle the initial VPC and DB setup then. Are we choosing AWS or GCP?' },
  { thread: 'Main', user: 'Nikunj', text: 'AWS makes the most sense since our organization\'s existing billing/tooling is all there.', isDecision: true },
  { thread: 'Main', user: 'Aarya', text: 'Sounds good. I will check the strict IAM roles we need to manage S3 bucket access.' },
  { thread: 'Main', user: 'Digambar', text: 'Should we consider a mobile app immediately? Construction workers are mostly on-site.' },
  { thread: 'Main', user: 'Nikunj', text: 'Absolutely in the future, but out of scope for MVP. We will build a highly responsive web app first.' },
  { thread: 'Main', user: 'Adarsh', text: 'How will we handle authentication? Subcontractors seeing other subcontractors\' bids would be a critical failure.' },
  { thread: 'Main', user: 'Nikunj', text: 'That\'s vital. We\'ll nail down the auth and RBAC strategy in the Backend thread.' },
  { thread: 'Main', user: 'Prathamesh', text: 'I\'ll also start looking at Stripe for the system subscription model so companies can pay for full platform access.' },
  { thread: 'Main', user: 'Aarya', text: 'And I will draft the initial infrastructure layout diagram.' },
  { thread: 'Main', user: 'Nikunj', text: 'Perfect. Let\'s split our technical deep-dives into Backend, Frontend, Infrastructure, and Integrations threads right now.' },
  { thread: 'Main', user: 'Digambar', text: 'I\'ll set up the Frontend thread to finalize our UI stack choices.' }
];

export const stage2_planning = [
  { thread: 'Backend', user: 'Nikunj', text: 'Let\'s finalize the backend DB and architecture.' },
  { thread: 'Backend', user: 'Prathamesh', text: 'I still feel MongoDB\'s aggregation pipeline could handle generating our complex project dashboards really well.' },
  { thread: 'Backend', user: 'Nikunj', text: 'The problem is transactional guarantees across bids and project budgets. A bid acceptance must atomically update the project\'s financial totals. I explicitly reject MongoDB for this because managing multi-document ACID transactions under high load might lead to race conditions.' },
  { thread: 'Backend', user: 'Prathamesh', text: 'That makes total sense. Postgres with JSONB it is.', isDecision: true },
  { thread: 'Backend', user: 'Nikunj', text: 'For API design, should we implement GraphQL or REST?' },
  { thread: 'Backend', user: 'Digambar', text: 'REST is standard, but a GraphQL layer helps the frontend avoid overfetching for those really complex project summary screens.' },
  { thread: 'Backend', user: 'Nikunj', text: 'Let\'s stick to REST for MVP to guarantee fast delivery. We can introduce a GraphQL BFF layer later if overfetching becomes an issue.' },
  { thread: 'Backend', user: 'Prathamesh', text: 'What about the auth strategy? Stateful sessions in Redis or stateless JWTs?' },
  { thread: 'Backend', user: 'Nikunj', text: 'I prefer short-lived JWTs paired with refresh tokens stored in httpOnly secure cookies. It mitigates XSS and CSRF risks while maintaining stateless scalability.', isDecision: true },
  { thread: 'Backend', user: 'Prathamesh', text: 'I will implement that exact auth flow today.' },
  { thread: 'Frontend', user: 'Digambar', text: 'Moving to our framework choice: Next.js vs raw React with Vite.' },
  { thread: 'Frontend', user: 'Adarsh', text: 'Next.js gives us robust SSR, which might be useful for SEO if we have public-facing project bidding pages.' },
  { thread: 'Frontend', user: 'Digambar', text: 'Actually, BuildBoard is almost entirely authenticated behind a login wall. SEO isn\'t a priority for the app itself. Vite will give us significantly faster build times locally.' },
  { thread: 'Frontend', user: 'Nikunj', text: 'Agreed on Vite. What about frontend state management? Redux?', isDecision: true },
  { thread: 'Frontend', user: 'Digambar', text: 'Redux involves too much boilerplate. I propose Zustand for global state, and React Query specifically for server caching.', isDecision: true },
  { thread: 'Frontend', user: 'Adarsh', text: 'Sounds solid. And component library?' },
  { thread: 'Frontend', user: 'Digambar', text: 'Let\'s use Tailwind CSS with Shadcn UI. It gives us fully accessible components that we can heavily customize without fighting rigid default styles.', isDecision: true },
  { thread: 'Frontend', user: 'Nikunj', text: 'Excellent choices. Digambar, you draft the initial dashboard shell.' },
  { thread: 'Frontend', user: 'Digambar', text: 'I\'ll scaffold the repository and push the base layout by tonight.' },
  { thread: 'Infrastructure', user: 'Aarya', text: 'AWS setup is underway. For our container strategy, are we leaning towards EKS (Kubernetes) or ECS?' },
  { thread: 'Infrastructure', user: 'Nikunj', text: 'EKS is probably overkill for our current engineering footprint. ECS with Fargate gives us serverless Docker execution without the control plane maintenance.', isDecision: true },
  { thread: 'Infrastructure', user: 'Aarya', text: 'ECS on Fargate it is. I\'ll write the Terraform modules for the target groups and the ECS cluster.' },
  { thread: 'Infrastructure', user: 'Adarsh', text: 'What about CI/CD? Are we spinning up Jenkins or using a hosted service?' },
  { thread: 'Infrastructure', user: 'Aarya', text: 'Jenkins is a headache. Let\'s establish our CI/CD pipeline purely through GitHub Actions. We can build images, push to ECR, and trigger ECS service updates.', isDecision: true },
  { thread: 'Infrastructure', user: 'Nikunj', text: 'Sounds robust. We must have strict network separation between staging and production.' },
  { thread: 'Infrastructure', user: 'Aarya', text: 'I will provision completely isolated VPCs across different subnets. Adarsh, can you outline the QA environments you need?' },
  { thread: 'Infrastructure', user: 'Adarsh', text: 'Just one staging environment that mirrors prod architecture exactly is fine for now.' },
  { thread: 'Infrastructure', user: 'Aarya', text: 'Noted.' },
  { thread: 'Integrations', user: 'Prathamesh', text: 'We need to decide on a document signing integration for the subcontractor compliance forms.' },
  { thread: 'Integrations', user: 'Nikunj', text: 'Could we use DocuSign\'s embedded signing API?' },
  { thread: 'Integrations', user: 'Prathamesh', text: 'Yes, but integrating their webhooks local testing can be painful.' },
  { thread: 'Integrations', user: 'Nikunj', text: 'We need to definitively establish how we consume document status updates. A background cron job polling their API, or processing webhooks?' },
  { thread: 'Integrations', user: 'Prathamesh', text: 'Without a queue, relying purely on real-time webhooks is dangerous; if our API drops, we lose signature events entirely.' },
  { thread: 'Integrations', user: 'Aarya', text: 'Let\'s put an SQS queue in front of our webhook receiver to guarantee event delivery.' },
  { thread: 'Integrations', user: 'Nikunj', text: 'Yes. Without an event buffer, a massive burst of document signatures from multiple projects could overwhelm our database workers.' },
  { thread: 'Integrations', user: 'Prathamesh', text: 'Let\'s resolve webhook vs polling then: we will use webhooks backed strictly by SQS instead of cron polling.', isDecision: true },
  { thread: 'Integrations', user: 'Nikunj', text: 'Perfect. We also need standard AWS S3 logic for general blueprint PDF uploads.' },
  { thread: 'Integrations', user: 'Prathamesh', text: 'I will handle generating those S3 pre-signed URLs.' },
  { thread: 'Integrations', user: 'Digambar', text: 'Prathamesh, please ensure the Swagger docs for those endpoints are updated so I can integrate them.' },
  { thread: 'Integrations', user: 'Prathamesh', text: 'I\'ll publish the Swagger spec this afternoon.' },
  { thread: 'Main', user: 'Nikunj', text: 'Plans are locked in guys. Let\'s move to the development phase.' }
];

export const stage3_development = [
  { thread: 'Main', user: 'Nikunj', text: 'Sprint 1 Development begins now. Keep cross-team blockers visible here.' },
  { thread: 'Backend', user: 'Nikunj', text: 'I have pushed the initial relational schema for Projects, Subcontractors, and Bids.' },
  { thread: 'Frontend', user: 'Digambar', text: 'I\'ve started hitting the local backend, but I am facing severe CORS errors when POSTing to `/api/auth/login`.' },
  { thread: 'Backend', user: 'Nikunj', text: 'Ah, my bad. My Express middleware is blocking the Vite default port 5173. I\'ll add it to the CORS whitelist immediately.' },
  { thread: 'Frontend', user: 'Digambar', text: 'Thanks. CORS is fixed, I can log in locally.' },
  { thread: 'Integrations', user: 'Prathamesh', text: 'The DocuSign webhook receiver is functional. I am catching events using ngrok right now.' },
  { thread: 'Infrastructure', user: 'Aarya', text: 'The staging ECS cluster has been created. The Terraform apply went smoothly.' },
  { thread: 'Backend', user: 'Nikunj', text: 'Prathamesh, please review my PR for the Bid submission controller.' },
  { thread: 'Backend', user: 'Prathamesh', text: 'Wait, I found a severe race condition in the Bid submission endpoint. If two subcontractors submit a bid for the exact same project time slot slot at the same millisecond, the availability check might pass for both before either transaction commits.' },
  { thread: 'Backend', user: 'Nikunj', text: 'Without an explicit table lock or unique constraint on the slot column, they could both reserve it. Good catch.' },
  { thread: 'Backend', user: 'Prathamesh', text: 'I will implement an EXCLUDE constraint on the table using tsrange to prevent overlapping time segments entirely at the database level.' },
  { thread: 'Backend', user: 'Nikunj', text: 'Fantastic. I\'m shifting focus to the hierarchical project dashboard query.' },
  { thread: 'Frontend', user: 'Digambar', text: 'I built the project dashboard table, but the `/api/projects/all` endpoint takes almost 4.5 seconds to respond. That\'s a show-stopping performance bottleneck.' },
  { thread: 'Backend', user: 'Nikunj', text: 'Let me look at the APM logs. Yikes, the ORM is triggering an N+1 query. It is sequentially looking up subcontractor profile details for every single bid attached to the projects.' },
  { thread: 'Backend', user: 'Nikunj', text: 'Actually, we\'re switching from TypeORM\'s lazy loading to explicit query builders with INNER JOINs because this automatic eager loading is killing our database CPU and stalling response times.' },
  { thread: 'Backend', user: 'Prathamesh', text: 'I can help optimize those. We could use a lateral join to only fetch the top 3 competitive bids per subcontractor natively in SQL.' },
  { thread: 'Backend', user: 'Nikunj', text: 'I have pushed a rewrite of that controller using explicit joins. Digambar, query the endpoint again.' },
  { thread: 'Frontend', user: 'Digambar', text: 'Response time is down to ~250ms. Much better.' },
  { thread: 'Infrastructure', user: 'Aarya', text: 'Hey guys, I noticed a major security concern while reviewing network traffic on staging. The S3 pre-signed URLs for blueprint downloads are set with a TTL of 7 days. If a URL is leaked, anyone can view sensitive docs.' },
  { thread: 'Backend', user: 'Prathamesh', text: 'That\'s a dangerous oversight. I will drop the expiration duration to exactly 15 minutes immediately.' },
  { thread: 'Infrastructure', user: 'Aarya', text: 'Appreciate the fast turnaround on that security patch.' },
  { thread: 'Integrations', user: 'Prathamesh', text: 'I\'ve hit a brick wall with DocuSign. Their composite templates API throws vague 400 errors whenever we try to dynamically append our custom checklist to the standard construction NDA.' },
  { thread: 'Integrations', user: 'Nikunj', text: 'Did their developer support offer any workarounds?' },
  { thread: 'Integrations', user: 'Prathamesh', text: 'They claim it\'s a limitation of our Sandbox API plan, and the workaround is incredibly complex.' },
  { thread: 'Integrations', user: 'Nikunj', text: 'We cannot let this block compliance testing. Actually, instead of DocuSign we\'re going with HelloSign (Dropbox Sign) for MVP. I reviewed their docs and their embedded signing mechanism handles dynamic custom fields way better.', isDecision: true },
  { thread: 'Integrations', user: 'Prathamesh', text: 'Alright, ripping out the DocuSign SDK and pivoting the entire integration to HelloSign today.' },
  { thread: 'Frontend', user: 'Digambar', text: 'Does HelloSign provide a React SDK for the embedded frames?' },
  { thread: 'Integrations', user: 'Prathamesh', text: 'Yes, they have a dedicated package out of the box. I will post the integration snippet in your thread.' },
  { thread: 'Frontend', user: 'Digambar', text: 'I am working on the generic document viewer UI for blueprints now. Should I load the PDFs into an iframe natively or use a parser library?' },
  { thread: 'Frontend', user: 'Adarsh', text: 'Without a proper renderer, a browser iframe might outright crash on iPhones. Some of those construction blueprints are 60MB+.' },
  { thread: 'Frontend', user: 'Digambar', text: 'Good point. I\'ll implement react-pdf with virtualized rendering so it only mounts the exact pages currently visible on screen.', isDecision: true },
  { thread: 'Infrastructure', user: 'Aarya', text: 'I linked GitHub Actions to sync the Vite build output to our S3 edge bucket, fronted by CloudFront.' },
  { thread: 'Infrastructure', user: 'Aarya', text: 'Wait, hard refreshing the app on staging returns a 404 Access Denied.' },
  { thread: 'Frontend', user: 'Digambar', text: 'That happens with SPAs. You need to configure the CloudFront distribution to gracefully fallback to `index.html` on 404 errors.' },
  { thread: 'Infrastructure', user: 'Aarya', text: 'CloudFront custom error responses updated. Refreshing works now.' },
  { thread: 'Backend', user: 'Nikunj', text: 'Prathamesh, is the Stripe integration for organization subscriptions functional?' },
  { thread: 'Integrations', user: 'Prathamesh', text: 'Mostly done. The `invoice.payment_succeeded` webhook is actively upgrading the tenant\'s tier in the database.' },
  { thread: 'Backend', user: 'Nikunj', text: 'Does the controller handle arbitrary retries? Stripe occasionally duplicates webhook event dispatches.' },
  { thread: 'Integrations', user: 'Prathamesh', text: 'Without an idempotency key check on the webhook processor, we might process a subscription upgrade multiple times, skewing internal metrics.' },
  { thread: 'Backend', user: 'Nikunj', text: 'Let\'s create a `processed_stripe_events` table just to log and skip duplicate IDs permanently.' },
  { thread: 'Integrations', user: 'Prathamesh', text: 'I will write that migration now.' },
  { thread: 'Frontend', user: 'Digambar', text: 'The auth flow on staging keeps intermittently rejecting users with an "Invalid Token" response just milliseconds after successful login.' },
  { thread: 'Backend', user: 'Nikunj', text: 'Are the staging UI and staging API on different subdomains? Yes, `staging.buildboard.com` and `api.staging.buildboard.com`.' },
  { thread: 'Backend', user: 'Nikunj', text: 'The default `SameSite=Strict` cookie policy is blocking the cross-subdomain handoff. I\'ll deploy a fix pushing it to `SameSite=Lax`.' },
  { thread: 'Frontend', user: 'Digambar', text: 'Tested. The token handoff is perfectly stable now.' },
  { thread: 'Testing', user: 'Adarsh', text: 'I am adding our initial Cypress end-to-end specs. Cypress is constantly flaking out on the HelloSign iframe rendering though.' },
  { thread: 'Testing', user: 'Adarsh', text: 'It\'s throwing cross-origin frame isolation errors during the test runs.' },
  { thread: 'Frontend', user: 'Digambar', text: 'I can inject a mock configuration for the HelloSign SDK during standard `NODE_ENV=test` runs so it bypasses the iframe and resolves the promise directly.', isDecision: true },
  { thread: 'Testing', user: 'Adarsh', text: 'That will stabilize the test suite. Please add that mock.' },
  { thread: 'Main', user: 'Nikunj', text: 'Excellent progress. Development for v1 is functionally complete. Moving strictly to Testing phase.' },
  { thread: 'Main', user: 'Aarya', text: 'Infrastructure is primed for formal load testing when you guys are ready.' }
];

export const stage4_testing = [
  { thread: 'Testing', user: 'Adarsh', text: 'Kicking off the formal QA cycle. The comprehensive Cypress e2e suites are executing.' },
  { thread: 'Testing', user: 'Adarsh', text: 'Cypress found our first bug during the automated file upload run. When uploading a 20MB compliance archive, the UI just hangs indefinitely.' },
  { thread: 'Frontend', user: 'Digambar', text: 'The Axios interceptor isn\'t tracking the raw upload progress correctly. I will bind the `onUploadProgress` event handler to the Shadcn UI progress bar.' },
  { thread: 'Backend', user: 'Nikunj', text: 'Wait, ensure the Nginx proxy routing to our ECS containers has `client_max_body_size 50M` configured, otherwise it simply drops large payloads silently.' },
  { thread: 'Infrastructure', user: 'Aarya', text: 'Updating the ECS task definition and Nginx configurations now to permit 50MB uploads.' },
  { thread: 'Testing', user: 'Adarsh', text: 'Retested with Cypress. The progress bar renders and the file completes successfully.' },
  { thread: 'Testing', user: 'Adarsh', text: 'I just finished running the K6 load tests against staging. I simulated 2500 concurrent users accessing different project dashboards.' },
  { thread: 'Testing', user: 'Adarsh', text: 'The `GET /api/projects/search` endpoint tanked completely. Response times hit 8.5 seconds at peak.' },
  { thread: 'Backend', user: 'Nikunj', text: '8.5 seconds? Checking the Datadog APM traces now.' },
  { thread: 'Backend', user: 'Nikunj', text: 'The bottleneck is the complex regex text search traversing project descriptions and subcontractor tags. It\'s triggering a massive sequential table scan.' },
  { thread: 'Backend', user: 'Prathamesh', text: 'We explicitly decided against implementing Elasticsearch earlier to save infrastructure complexity. Should we spin up an ES cluster now?' },
  { thread: 'Backend', user: 'Nikunj', text: 'Actually, this isn\'t working, moving to PostgreSQL\'s native `tsvector` full-text search capability instead of basic `ILIKE` queries. It gives us highly indexed search speeds without the massive overhead of managing an Elasticsearch cluster.', isDecision: true },
  { thread: 'Backend', user: 'Prathamesh', text: 'I will write the migration to add the `tsvector` columns and deploy a GIN index on them.' },
  { thread: 'Testing', user: 'Adarsh', text: 'Ping me the moment that GIN index migration is applied to staging.' },
  { thread: 'Backend', user: 'Nikunj', text: 'The migration just finished executing. Try the K6 suite again.' },
  { thread: 'Testing', user: 'Adarsh', text: 'Mind-blowing. Response time on identical load is now hovering around 120ms at p95. The GIN index crushed the bottleneck.' },
  { thread: 'Testing', user: 'Adarsh', text: 'Moving to deep security testing. I\'m running automated penetration tools against our REST controllers.' },
  { thread: 'Testing', user: 'Adarsh', text: 'I found a critical security vulnerability. The `GET /api/bids/:id` endpoint does not verify if the JWT user is actually an owner or associated subcontractor for that specific bid. That\'s a severe IDOR.' },
  { thread: 'Backend', user: 'Nikunj', text: 'Wow. That is a terrible oversight. A malicious user could iterate bid IDs indefinitely and expose competitor pricing.' },
  { thread: 'Backend', user: 'Nikunj', text: 'I am rewriting the RBAC middleware on that controller right now to strictly verify tenant ownership before returning the resource data.', isDecision: true },
  { thread: 'Backend', user: 'Nikunj', text: 'Patch deployed. Adarsh, verify the IDOR loophole is closed.' },
  { thread: 'Testing', user: 'Adarsh', text: 'Retesting sequence... I am receiving a 403 Forbidden with a separate tenant\'s token. Flaw is closed.' },
  { thread: 'Backend', user: 'Prathamesh', text: 'I noticed a major UX flaw while doing manual notification checks. The system emails subcontractors instantly on every single compliance document update. On large projects, this spams dozens of emails.' },
  { thread: 'Backend', user: 'Nikunj', text: 'Without a debounce mechanism, AWS SES will likely throttle our sending limits and mark us as a spam domain.' },
  { thread: 'Backend', user: 'Prathamesh', text: 'We originally chose instant transaction emails during planning, but we need to revisit this architectural decision. A daily digest batch job is much safer and less annoying.', isDecision: true },
  { thread: 'Backend', user: 'Nikunj', text: 'Agreed. A daily digest changes the architecture slightly but protects our reputation.' },
  { thread: 'Backend', user: 'Prathamesh', text: 'I will refactor the Redis worker to aggregate states and dispatch summary emails at 5 PM local.' },
  { thread: 'Frontend', user: 'Digambar', text: 'Found a subtle interaction bug on iPads. The draggable Kanban cards in the project board view lock up completely when touched.' },
  { thread: 'Frontend', user: 'Digambar', text: 'Resolved it. Had to forcefully apply `touch-action: none` to the CSS handle, otherwise iOS Safari intercepts the drag and tries to pan the viewport instead.' },
  { thread: 'Testing', user: 'Adarsh', text: 'Final regression tests are executing.' },
  { thread: 'Testing', user: 'Adarsh', text: 'All 340 Cypress tests are marked green.' },
  { thread: 'Testing', user: 'Adarsh', text: 'Load tests show completely sustained stability at 4500 RPS.' },
  { thread: 'Testing', user: 'Adarsh', text: 'Zero high severity CWEs from the pipeline dependency checks.' },
  { thread: 'Main', user: 'Nikunj', text: 'Phenomenal effort debugging everything, team.' },
  { thread: 'Main', user: 'Aarya', text: 'I am formally locking environments. We are clear for production.' }
];

export const stage5_deployment = [
  { thread: 'Infrastructure', user: 'Aarya', text: 'Initiating the production deployment sequence right now. The `main` branch is hard-locked.' },
  { thread: 'Infrastructure', user: 'Aarya', text: 'Provisioning the massive Production RDS instances. Multi-AZ is fully active and read replicas are spinning up.' },
  { thread: 'Backend', user: 'Nikunj', text: 'I am manually executing the core database schema migrations against the production cluster.' },
  { thread: 'Backend', user: 'Nikunj', text: 'Migrations committed. All 34 tables generated flawlessly.' },
  { thread: 'Infrastructure', user: 'Aarya', text: 'Deploying the ECS Fargate tasks for the API controllers and our background worker fleets.' },
  { thread: 'Frontend', user: 'Digambar', text: 'Production Vite payload triggered. GitHub Actions is uploading the bundle to the S3 edge bucket.' },
  { thread: 'Integrations', user: 'Prathamesh', text: 'I am switching the Stripe and HelloSign credentials from sandbox keys to live keys inside AWS Secrets Manager.' },
  { thread: 'Backend', user: 'Nikunj', text: 'The API load balancer health checks are all returning solid 200 OKs.' },
  { thread: 'Frontend', user: 'Digambar', text: 'The CloudFront edge cache invalidation finished. The buildboard.com frontend is officially live worldwide.' },
  { thread: 'Testing', user: 'Adarsh', text: 'Awesome. I am running a highly targeted smoke test suite directly against production using our internal beta organization.' },
  { thread: 'Testing', user: 'Adarsh', text: 'Hold on. The paid tier subscription creation is 500ing on the checkout return flow.' },
  { thread: 'Backend', user: 'Nikunj', text: 'Let me tail the Datadog logs. It says "Stripe Webhook signature verification failed".' },
  { thread: 'Integrations', user: 'Prathamesh', text: 'Oh man. I forgot to generate a separate Stripe Webhook Signing Secret specifically for the Live environment. The API is still validating incoming production webhooks using the test-mode secret string.' },
  { thread: 'Integrations', user: 'Prathamesh', text: 'I\'ll update the `STRIPE_WEBHOOK_SECRET` key in Secrets Manager immediately.' },
  { thread: 'Infrastructure', user: 'Aarya', text: 'I am forcing a rolling restart on the API ECS cluster to pull the new secrets into memory.' },
  { thread: 'Integrations', user: 'Prathamesh', text: 'Restart is finished. Adarsh, please trigger checkout again.' },
  { thread: 'Testing', user: 'Adarsh', text: 'Checkout is successful. The Stripe invoice webhook fired correctly and upgraded the test org to Pro tier. Production issue is fully resolved.' },
  { thread: 'Infrastructure', user: 'Aarya', text: 'I am mapping the PagerDuty on-call shifts to our new Datadog APM monitors to ensure we catch any further crashes in seconds.' },
  { thread: 'Frontend', user: 'Digambar', text: 'The Sentry dashboard is gorgeously quiet. Absolutely zero client-side exceptions bubbling up from real users.' },
  { thread: 'Main', user: 'Nikunj', text: 'Incredibly proud of everyone. BuildBoard MVP is officially launched.' },
  { thread: 'Main', user: 'Digambar', text: 'Stellar work folks! Going offline to sleep for a week.' },
  { thread: 'Main', user: 'Aarya', text: 'The platform architecture really paid off. Aarya signing off.' },
  { thread: 'Main', user: 'Adarsh', text: 'The QA board is empty. Great stability team. Adarsh signing off.' },
  { thread: 'Main', user: 'Prathamesh', text: 'Integrations are completely solid. Signing off.' }
];

export const allConversations = [
  ...stage1_ideation,
  ...stage2_planning,
  ...stage3_development,
  ...stage4_testing,
  ...stage5_deployment
];
